import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import NPMIcon from "@/components/Icons/NPM";
import GithubIcon from "@/components/Icons/Github";
import ProjectTile from "@/components/ProjectTile/ProjectTile";
import useViewport from "@/hooks/useViewport";
import LinkedinIcon from "@/components/Icons/Linkedin";
import cx from "classnames";
import { Button, Container, Stack, Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {
	isMobile: boolean;
}

export default function Home(props: HomeProps) {
	const { width } = useViewport();
	const isMobile = width < 586;
	const projects = [
		{
			number: "01",
			title: "Notion Blocks Package ",
			image:
				"https://assets.website-files.com/610db4fccfb55c2851d2f43f/612833417386b32f54dfeb96_Create%20a%20Blog%20in%20Notion-min.jpg",
			technologies: ["Typescript", "React", "Storybook"],
			description:
				"A NPM Package for React projects that use Notion as a CMS and want a library to closely mimic Notion's appearance while still allowing styling flexibility, accessibility and a single entry point.",
			links: [
				{
					icon: <GithubIcon />,
					url: "https://github.com/jaysongiroux/notion-blocks",
				},
				{
					icon: <NPMIcon />,
					url: "https://www.npmjs.com/package/notion-blocks",
				},
			],
		},
		{
			number: "02",
			title: "Pico Macro Pad",
			image:
				"https://github.com/jaysongiroux/pico-macro-pad/raw/master/git_assets/macro-pad-screen.jpg",
			technologies: ["Python", "3D Printing", "Circuits"],
			description:
				"Designed and documented for beginners that want to learn more about 3D printing, soldering, circuits, and coding. An open source 3D printable macro-pad built with accessible hardware and easy to modify python code to build your very own macro pad.",
			links: [
				{
					icon: <GithubIcon />,
					url: "https://github.com/jaysongiroux/pico-macro-pad",
				},
			],
		},
		{
			number: "03",
			title: "move-mouse",
			image:
				"https://s.yimg.com/uu/api/res/1.2/_ruFf55AtrcrG5izIYfCUg--~B/Zmk9ZmlsbDtoPTU0Mzt3PTg3NTthcHBpZD15dGFjaHlvbg--/https://o.aolcdn.com/images/dims?crop=1284%2C797%2C113%2C236&quality=85&format=jpg&resize=1600%2C993&image_uri=https%3A%2F%2Fs.yimg.com%2Fos%2Fcreatr-uploaded-images%2F2019-03%2Fc4096e10-4b50-11e9-bd7f-3b9704c9ec8c&client=a1acac3e1b3290917d92&signature=41c62820b05951d795a54c9b0a57398c9d1a3c8d.cf.webp",
			technologies: ["C++", "CMAKE", "Azure Kinect"],
			description:
				"Ever wanted to control your computer like Iron man? With the swipe and grab of your hand you can now click and drag on your screen using the Azure Kinect 3D camera.",
			links: [
				{
					icon: <GithubIcon />,
					url: "https://github.com/jaysongiroux/MoveMouse",
				},
				{
					icon: <LinkedinIcon />,
					url: "https://www.linkedin.com/feed/update/urn:li:activity:6671834721229537280/",
				},
			],
		},
	];

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={inter.className}>
				<Container maxWidth={"lg"}>
					<Container className={styles.HomeHero}>
						<Typography variant="h2" className={styles.HomeNameIs}>
							Hi, My name is
						</Typography>
						<Typography variant="h1" className={styles.HomeName}>
							Jason Giroux
						</Typography>
						<Typography variant="h3" className={styles.HomeTagName}>
							I code things for people to use
						</Typography>
						<Typography paragraph className={styles.HomeDescription}>
							I&apos;m a rhode Island based full stack developer that
							specializes in building exceptional digital experiences. I
							Currently work at{" "}
							<a href="hometap.com">Hometap Equity Partners</a> as a Full Stack
							Engineer E2. Get In Touch
						</Typography>
						<Button variant="outlined" className={styles.HomeContactButton}>
							<Typography variant="subtitle1">Get In Touch!</Typography>
						</Button>
					</Container>

					<Container className={styles.HomeHero}>
						<Typography variant="h3" className={styles.HomeFeaturedProjects}>
							Featured Projects
						</Typography>
						<Stack
							direction={{ sm: "column", md: "row" }}
							spacing={{ xs: 1, sm: 2, md: 4 }}
							justifyContent={{ sm: "unset", md: "space-between" }}
							alignItems={{ sm: "center", md: "unset" }}
						>
							{projects.map((project, key) => (
								<ProjectTile key={key} {...project} isMobile={isMobile} />
							))}
						</Stack>
					</Container>

					<Container className={cx(styles.HomeHero, styles.HomeContact)}>
						<Typography variant="h2" className={styles.HomeWhatDoYouThink}>
							So, What do you think?
						</Typography>
						<Typography variant="h1" className={styles.HomeGetInTouch}>
							Get In Touch
						</Typography>
						<Typography paragraph className={styles.HomeContactParagraph}>
							I love connecting and networking so lets talk - looking forward to
							hearing from you!
						</Typography>
						<Button className={styles.HomeContactButton}>Contact Me</Button>
					</Container>
				</Container>
			</main>
		</>
	);
}
